--April 10 🧠 Concept (Short)
--Subquery → query inside query
  
WITH customers AS (
    SELECT 101 AS customer_id, 'Alice' AS customer_name, 'India' AS country UNION ALL
    SELECT 102, 'Bob', 'India' UNION ALL
    SELECT 103, 'Charlie', 'USA' UNION ALL
    SELECT 104, 'David', 'UK' UNION ALL
    SELECT 105, 'Eva', 'India' UNION ALL
    SELECT 106, 'Frank', 'Germany'
),

orders AS (
    SELECT 1 AS order_id, 101 AS customer_id, 500 AS order_amount, 'DELIVERED' AS order_status, DATE '2023-01-05' AS order_date UNION ALL
    SELECT 2, 102, 300, 'CANCELLED', DATE '2023-01-10' UNION ALL
    SELECT 3, 101, 700, 'DELIVERED', DATE '2023-02-15' UNION ALL
    SELECT 4, 103, 400, 'PENDING', DATE '2023-02-20' UNION ALL
    SELECT 5, 104, 1200, 'DELIVERED', DATE '2023-03-01' UNION ALL
    SELECT 6, 102, 800, 'DELIVERED', DATE '2023-03-05' UNION ALL
    SELECT 7, 101, 200, 'CANCELLED', DATE '2023-03-10' UNION ALL
    SELECT 8, 105, 1500, 'DELIVERED', DATE '2023-03-15' UNION ALL
    SELECT 9, 106, 600, 'PENDING', DATE '2023-03-20'
)

-- 🟢 Q1: Customers Above Average Spend
-- Find customers whose total spend is greater than average customer spend.
-- 👉 Multi-step required

WITH customer_spend AS (
    SELECT customer_id, SUM(order_amount) AS total_spend
    FROM orders
    GROUP BY customer_id
),
avg_spend AS (
    SELECT AVG(total_spend) AS avg_total_spend
    FROM customer_spend
)
SELECT cs.customer_id, cs.total_spend
FROM customer_spend cs
JOIN avg_spend a
ON cs.total_spend > a.avg_total_spend;



-- 🟢 Q2: Orders Above Overall Average Amount
-- Find all orders where order_amount is greater than average order amount.

SELECT *
FROM orders
WHERE order_amount > (
    SELECT AVG(order_amount)
    FROM orders
);



-- 🟡 Q3: Top Spending Customers (Above 1000)
-- Find customers whose total spend is greater than 1000.
-- 👉 Solve using:
-- Subquery

SELECT customer_id, SUM(order_amount) AS total_spend
FROM orders
GROUP BY customer_id
HAVING SUM(order_amount) > 1000;

-- 👉 Using CTE

WITH customer_spend AS (
    SELECT customer_id, SUM(order_amount) AS total_spend
    FROM orders
    GROUP BY customer_id
)
SELECT *
FROM customer_spend
WHERE total_spend > 1000;



-- 🟡 Q4: Customers with Latest Order After Feb 2023
-- Find customers whose latest order date is after '2023-02-01'.
-- 👉 Think aggregation + filtering

SELECT customer_id, MAX(order_date) AS latest_order
FROM orders
GROUP BY customer_id
HAVING MAX(order_date) > DATE '2023-02-01';



-- 🟡 Q5: Customers Who Never Cancelled Any Order
-- Find customers who have placed orders but never cancelled.
-- 👉 Trick: exclusion logic

SELECT customer_id
FROM orders
GROUP BY customer_id
HAVING SUM(CASE WHEN order_status = 'CANCELLED' THEN 1 ELSE 0 END) = 0;



-- 🔴 Q6: Customers Whose Spend is Above Their Country Average
-- Find customers whose total spend is greater than average spend of their country.
-- 👉 Multi-level aggregation 🔥

WITH customer_spend AS (
    SELECT c.customer_id, c.country, SUM(o.order_amount) AS total_spend
    FROM customers c
    JOIN orders o
    ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.country
),
country_avg AS (
    SELECT country, AVG(total_spend) AS avg_country_spend
    FROM customer_spend
    GROUP BY country
)
SELECT cs.customer_id, cs.country, cs.total_spend
FROM customer_spend cs
JOIN country_avg ca
ON cs.country = ca.country
WHERE cs.total_spend > ca.avg_country_spend;



-- 🔴 Q7: Second Highest Order Amount
-- Find the second highest order_amount.
-- 👉 Avoid simple LIMIT tricks (think properly)

SELECT MAX(order_amount) AS second_highest
FROM orders
WHERE order_amount < (
    SELECT MAX(order_amount)
    FROM orders
);



-- 🔴 Q8: Customers with More Orders Than Average Customer
-- Find customers whose total number of orders is greater than average orders per customer.

WITH order_counts AS (
    SELECT customer_id, COUNT(*) AS total_orders
    FROM orders
    GROUP BY customer_id
),
avg_orders AS (
    SELECT AVG(total_orders) AS avg_order_count
    FROM order_counts
)
SELECT oc.customer_id, oc.total_orders
FROM order_counts oc
JOIN avg_orders a
ON oc.total_orders > a.avg_order_count;



-- 🔴 Q9: Revenue of Top 2 Customers
-- Find total revenue generated by top 2 highest spending customers.
-- 👉 Step-wise thinking required

WITH customer_spend AS (
    SELECT customer_id, SUM(order_amount) AS total_spend
    FROM orders
    GROUP BY customer_id
),
ranked_customers AS (
    SELECT customer_id, total_spend,
           RANK() OVER (ORDER BY total_spend DESC) AS rnk
    FROM customer_spend
)
SELECT SUM(total_spend) AS total_revenue
FROM ranked_customers
WHERE rnk <= 2;



-- 🔴 Q10: Customers Who Contribute to Top 50% Revenue
-- Find customers who contribute to top 50% of total revenue.

WITH customer_spend AS (
    SELECT customer_id, SUM(order_amount) AS total_spend
    FROM orders
    GROUP BY customer_id
),
total_revenue AS (
    SELECT SUM(total_spend) AS total_rev
    FROM customer_spend
),
ranked AS (
    SELECT cs.customer_id, cs.total_spend,
           SUM(cs.total_spend) OVER (ORDER BY cs.total_spend DESC) AS running_total
    FROM customer_spend cs
)
SELECT r.customer_id, r.total_spend
FROM ranked r
JOIN total_revenue t
ON r.running_total <= 0.5 * t.total_rev;
